# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 760ed384e036b5f85ca2fca292a5ae075da45a132bbe7906a05cf2b37b410ffcc12bafde99d18417dcc2e0c9f96cf78fecd04496bf10297167859d7aebe778f7

test:
  secret_key_base: 9c511462f5b1e98e97f9b9dcb9af054bb51ab5d751573288fb44aed04d51ed8d073c4efa21852ec93f5566aa14f6478b3373c4f8dfd939fc475fecdcafb23b64

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
